name: Continuous Integration
on: [push, pull_request, release]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-22.04,
          ubuntu-20.04,
          macos-13,
          macos-12,
          windows-2022,
          windows-2019,
        ]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run-script testCopyCases
    - run: npm run-script testSnapshot
    - run: npm run-script buildLint
    - run: npm run-script buildTypeScript
    - run: npm run-script buildEsbuild
    - run: npm run-script buildJasmine
  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run-script buildTypeScript
    - run: npm run-script buildEsbuild
    - run: rm -r node_modules
    - run: "sed -i \"s/\\\"version\\\": \\\"0.0.0\\\",/\\\"version\\\": \\\"${GITHUB_REF/refs\\/tags\\/v/}\\\",/g\" package.json"
    - run: npx @vscode/vsce publish -p ${{ secrets.VSCE_TOKEN }}
