name: Continuous Integration
on: [push, pull_request, release]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04,
          ubuntu-18.04,
          macos-11,
          macos-10.15,
          windows-2022,
          windows-2019,
          windows-2016
        ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run-script testCopyCases
    - run: npm run-script testSnapshot
  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: npm i -g vsce
    - run: vsce login skitscript
      env:
        VSCE_STORE: file
        VSCE_PAT: ${{ secrets.NPM_TOKEN }}
    - run: vsce publish ${GITHUB_REF/refs\\/tags\\/v/}
